image: '{% endraw %}{{ build_image_name(\"dex\", False) }}{% raw %}'

nodeSelector:
  node-role.kubernetes.io/infra: ''

tolerations:
  - key: "node-role.kubernetes.io/bootstrap"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoSchedule"

replicas: 2

# grpc support
grpc: false

# https termination by dex itself
https: true

service:
  clusterIP: '{% endraw %}{{ salt.metalk8s_network.get_oidc_service_ip() }}{% raw %}'

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: "nginx-control-plane"
  path: /oidc
  hosts:
    - null

extraVolumes:
  - name: dex-login
    configMap:
      name: dex-login

extraVolumeMounts:
  - name: dex-login
    mountPath: /web/themes/scality

certs:
  web:
    create: false
  grpc:
    create: false

config:
  issuer: '{% endraw %}https://{{ grains.metalk8s.control_plane_ip }}:8443/oidc{% raw %}'
  web:
    tlsCert: /etc/dex/tls/https/server/tls.crt
    tlsKey: /etc/dex/tls/https/server/tls.key
  frontend:
    theme: "scality"
    issuer: "MetalK8s"

  connectors: {}

  oauth2:
    alwaysShowLoginScreen: true
    skipApprovalScreen: true
    responseTypes: ["code", "token", "id_token"]

  expiry:
    signingKeys: "6h"
    idTokens: "24h"

  staticClients:
  - id: oidc-auth-client
    redirectURIs:
    - 'urn:ietf:wg:oauth:2.0:oob'
    name: 'oidc-auth-client'
    secret: "lkfa9jaf3kfakqyeoikfjakf93k2l"
    trustedPeers:
    - metalk8s-ui
    - grafana-ui
    - metalk8s-cli
  - id: metalk8s-ui
    redirectURIs:
    - '{% endraw %}https://{{ grains.metalk8s.control_plane_ip }}:8443/oauth2/callback{% raw %}'
    name: 'MetalK8s UI'
    secret: "ybrMJpVMQxsiZw26MhJzCjA2ut"
  - id: grafana-ui
    name: 'Grafana UI'
    redirectURIs:
    - '{% endraw %}https://{{ grains.metalk8s.control_plane_ip }}:8443/grafana/login/generic_oauth{% raw %}'
    secret: "4lqK98NcsWG5qBRHJUqYM1"
  - id: metalk8s-cli
    name: MetalK8s CLI
    redirectURIs:
    - http://localhost
    - http://127.0.0.1
    secret: jfakfka9i32242k4j2k42j42249kah

  staticPasswords:
    - email: "admin@metalk8s.invalid"
      # bcrypt hash of the string "password"
      hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      username: "admin"
      userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
